version: 2.1

jobs:
  build:
    docker:
      - image: cimg/rust:1.60
    steps:
      - checkout
      - run: cargo --version
      - run:
          name: "run test"
          command: "cargo test"

